//quotes and authors which will be displayed randomly
const quotes = [
    {
        quote: '"The only way to do great work is to love what you do."',
        author: "- Steve Jobs"
    },
    {
        quote: '"Innovation distinguishes between a leader and a follower."',
        author: "- Steve Jobs"
    },
    {
        quote: '"The future belongs to those who believe in the beauty of their dreams."',
        author: "- Eleanor Roosevelt"
    },
    {
        quote: '"The greatest glory in living lies not in never falling, but in rising every time we fall."',
        author: "- Nelson Mandela"
    },
    {
        quote: '"The way to get started is to quit talking and begin doing."',
        author: "- Walt Disney"
    },
    {
        quote: '"Don\'t watch the clock; do what it does. Keep going."',
        author: "- Sam Levenson"
    },
    {
        quote: '"Believe you can and you\'re halfway there."',
        author: "- Theodore Roosevelt"
    },
    {
        quote: '"Success is not final, failure is not fatal: It is the courage to continue that counts."',
        author: "- Winston Churchill"
    },
    {
        quote: '"You miss 100% of the shots you don\'t take."',
        author: "- Wayne Gretzky"
    },
    {
        quote: '"The best way to predict the future is to create it."',
        author: "- Peter Drucker"
    }
];

//function to generatae a greeting message according to daytime
function generateHeading(){
    const welcomeHeading = document.getElementById("welcome");
    let now = new Date();
    const hours = now.getHours();
    let welcomeString;

    if(hours>=20 || hours <3 )
    welcomeString = "Let's start our night with a new quote";

    else if(hours>=3 && hours<=11)
    welcomeString = "Let's start our morning with a new quote";

    else if(hours>11 && hours<=15)
    welcomeString = "Let's start our noon with a new quote";

    else
    welcomeString = "Let's start our evening with a new quote";

    welcomeHeading.innerHTML = welcomeString;
}
generateHeading();

//function to get a random quote
function generateRandomQuote() {
    const randomIndex = Math.floor(Math.random() * quotes.length);
    const randomQuote = quotes[randomIndex];
    
    document.getElementById('quote').textContent = randomQuote.quote;
    document.getElementById('author').textContent = randomQuote.author;
}
generateRandomQuote();

//function to generate a random quote
let colorselect;
function getRandomColor() {
    const colors = [
    {bgcolor:"#ffaeae", box:"#ffebeb", hover:"#d76969"},
    {bgcolor:"#ffdfae", box:"#fff6e9", hover:"#dba860"},
    {bgcolor:"#ecffae", box:"#faffe8", hover:"#b6d061"},
    {bgcolor:"#b5ffae", box:"#eaffe8", hover:"#5bbd52"},
    {bgcolor:"#aefffb", box:"#eafffe", hover:"#55bbb4"},
    {bgcolor:"#aec1ff", box:"#eaefff", hover:"#5b74c6"},
    {bgcolor:"#e3aeff", box:"#f7e9ff", hover:"#ba74e2"},
    {bgcolor:"#ffaed1", box:"#ffedf5", hover:"#e370a4"}
    ];
    const randomIndex1 = Math.floor(Math.random() * colors.length);
    colorselect =  colors[randomIndex1];
}

//function to update colour of background and button to color generated by getRandomColor when program loaded
function updatecolor() {
    getRandomColor();
    document.body.style.backgroundColor = colorselect.bgcolor;
    document.getElementById('generateBtn').style.backgroundColor = colorselect.bgcolor;
    document.getElementById('quoteBox').style.background = colorselect.box;
}
updatecolor();

//this will ge invoked when button clicked as the colour of the button is different
function updatecolor2() {
    getRandomColor();
    document.body.style.backgroundColor = colorselect.bgcolor;
    document.getElementById('generateBtn').style.backgroundColor = colorselect.hover;
    document.getElementById('quoteBox').style.background = colorselect.box;
}

//adding actionListener events for the buttonclick
document.getElementById('generateBtn').addEventListener('click', generateRandomQuote);
document.getElementById('generateBtn').addEventListener('click', generateHeading);
document.getElementById('generateBtn').addEventListener('click',updatecolor2);

document.getElementById('generateBtn').addEventListener('mouseenter', () => (document.getElementById('generateBtn').style.backgroundColor = colorselect.hover) );
document.getElementById('generateBtn').addEventListener('mouseleave', () => (document.getElementById('generateBtn').style.backgroundColor = colorselect.bgcolor) );
document.getElementById('generateBtn').addEventListener('mouseover', () => (document.getElementById('generateBtn').style.backgroundColor = colorselect.hover) );
